apiVersion: v1
kind: Service
metadata:
  labels:
    app: shale-tasks-api
  name: shale-tasks-api
spec:
  type: LoadBalancer
  ports:
    - port: 1323
      targetPort: 1323
      protocol: TCP
  selector:
    app: shale-tasks-api